name: Build Win64

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies [apt]
        run: |
          sudo apt-get update
          sudo apt install libpcap-dev -y
      - name: Install dependencies [go]
        run: |
          go get .
      - name: Build
        run: |
          export GOARCH=amd64
          export GOOS=windows
          VERSION=$(git describe --tags 2>/dev/null || git rev-parse --short HEAD)
          go build -o pcap2har.exe -ldflags "-X github.com/colinnewell/pcap-cli/cli.Version=$VERSION" cmd/pcap2har/*.go
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: pcap2har.exe
          path: pcap2har.exe
